customhost = "employee.c4foeijkfn1j.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chuajiaxin-bucket"
customregion = "us-east-1a"
